=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommjunity.github.io/recipe.xsd"
xmlns="https://cazzscookingcommjunity.github.io/recipe.xsd"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence>
        <xs:element name="LowSugar"/>
        <xs:element name="GlutenFree"/>
        <xs:element name="EggFree"/>
        <xs:element name="NA"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="amount" type="xs:float"/>
    <xs:attribute name="unit" type="unitType"/>
</xs:complexType>


<xs:complexType name="recipeType">
    <xs:all>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="cookTime" type="xs:string"/>
        <xs:element name="recipeCategory" type="xs:string"/>
        <xs:element name="ingredient" type="ingredientType"/>
        <xs:element name="step" type="xs:string"/>
        <xs:element name="yield" type="xs:integer"/>
        <xs:element name="diet" type="dietType"/>
        <xs:element name="prepTime" type="xs:time"/>
        <xs:element name="comment" type="xs:string"/>
        <xs:element name="thumbnailUrl" type="xs:anyURI"/>
        <xs:element name="image" type="xs:anyURI"/>
    </xs:all>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/rice_bubble_slice.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Rice Bubble Slice</title>
<filename>rice_bubble_slice.xml</filename>
<thumbnail>rice_bubble_slice.jpeg</thumbnail>
<category>Snack</category>
<category>Dessert</category>
<category>Sweets</category>
<diet>GFO</diet>
<diet>Vegetarian</diet>
<yield>24</yield>
<prepTime>PT15M</prepTime>
<cookTime>PT3H</cookTime>
<comment>c/o mykidslickthebowl with cazzie tweaks</comment>
<ingredient>30gms butter</ingredient>
<ingredient>3 TBsp honey</ingredient>
<ingredient>1/2 cup Mayvers peanut butter</ingredient>
<ingredient>3 cups rice bubbles (gluten free if desired or regular)</ingredient>
<step>Grease a small loaf/slice tray and line with baking paper, then set aside.</step>
<step>In a saucepan melt the butter, then add the honey and stir until combined.</step>
<step>Remove from heat and stir in peanut butter.</step>
<step>Pour in rice bubbles and stir until all the rice bubbles are coated.</step>
<step>Pour into prepared tray and push down with the back of a spoon.</step>
<step>(You can sprinkle top with sprinkles if desired at this stage) place in fridge for 3 hours.</step>
<step>Once set cut into small squares.</step>
<step>Once slice is set, before cutting you can pour over melted 200gm block of chocolate.</step>
<step>Replace in fridge until top is set then cut into squares.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/paleo_chocolate_chip_cookies.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Paleo Chocolate Chip Cookies </title>
  <filename>paleo_chocolate_chip_cookies.xml</filename>
  <comment>c/o ambitious kitchen</comment>
  <thumbnail>paleo_choc_chip_cookies.jpeg</thumbnail>
  <category>Sweets</category>
  <diet>Paleo</diet>
  <diet>GlutenFree</diet>
  <ingredient>1 egg (room temperature)</ingredient>
  <ingredient>1 teaspoon vanilla extract </ingredient>
  <ingredient>1/3 cup coconut oil</ingredient>
  <ingredient>1/2 cup coconut sugar </ingredient>
  <ingredient>1 cup almond or hazelnut flour</ingredient>
  <ingredient>1/4 cup coconut flour</ingredient>
  <ingredient>1/2 teaspoon baking soda</ingredient>
  <ingredient>3/4 cup choc chips (diary free if required)</ingredient>
  <ingredient>Pinch of salt</ingredient>
  <step>Preheat oven to 180C.</step>
  <step>Line a baking sheet and set aside.</step>
  <step>Melt coconut oil and set aside (should not be hot when adding other ingredients.</step>
  <step>) In a bowl mix flours, salt, sugar and baking soda.</step>
  <step>Whisk to mix and remove any lumps.</step>
  <step>In the cooled coconut oil add the vanilla extract and egg.</step>
  <step>Whisk until combined.</step>
  <step>Pour wet ingredients into dry and mix until dough forms.</step>
  <step>Fold in 1/2 cup of choc chips.</step>
  <step>Place Table spoon amounts on baking tray and sprinkle a couple of extra choc chips on top of each cookie.</step>
  <step>Cook for 8-10 minutes or until golden.</step>
  <step>Cool on tray then remove to a cooling rack.</step>
  <step>Store in an airtight container once completely cold.</step>
  <step>Yum yum!.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/a_test.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd">
  <title>Acquacotta</title>
  <filename>acquacotta.xml</filename>
  <thumbnail>acquacotta.jpeg</thumbnail>
  <category>Soup</category>
  <diet>Vegetarian</diet>
  <yield>4</yield>
  <prepTime>PT15M</prepTime>
  <cookTime>PT1H15M</cookTime>
  <ingredient>2-3 Tbsp olive oil</ingredient>
  <ingredient>2-3 garlic cloves crushed</ingredient>
  <ingredient>Pinch of chili</ingredient>
  <ingredient>2-4 celery stalks chopped</ingredient>
  <ingredient>1-2 carrots chopped</ingredient>
  <ingredient>1 cup white wine</ingredient>
  <ingredient>6 cups water</ingredient>
  <ingredient>2 stock cubes</ingredient>
  <ingredient>2 cans chopped tomatoes</ingredient>
  <ingredient>salt and pepper to taste</ingredient>
  <ingredient>1 cup ricotta cheese (optional)</ingredient>
  <ingredient>4 eggs (optional)</ingredient>
  <ingredient>4 slices stale bread (optional)</ingredient>
  <ingredient>Any Italian herbs (parsley or basil) you have on hand (optional)</ingredient>
  <step>Heat oil in large pot and cook garlic on low for 5 minutes.</step>
  <step>Add carrots and celery and cook for a further 5 minutes.</step>
  <step>Sprinkle in chili and stir well, then add water, stock cubes, tomatoes, wine, and salt and pepper.</step>
  <step>Bring to boil then reduce to a simmer and cook for 1 hour.</step>
  
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/gluten_free_brownie.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd">
  <title>Gluten Free Brownie</title>
  <filename>gluten_free_brownie.xml</filename>
  <thumbnail>gluten_free_brownies.jpeg</thumbnail>
  <category>Sweets</category>
  <diet>GlutenFree</diet>
  <comment>c/o Cacao powder with cazzie tweaks</comment>
  <ingredient>1 cup cacao powder</ingredient>
  <ingredient>1 cup hazelnut or almond meal</ingredient>
  <ingredient>1 cup raw sugar</ingredient>
  <ingredient>4 eggs beaten</ingredient>
  <ingredient>1/3 cup milk of your choice</ingredient>
  <ingredient>1/2 cup coconut oil melted and cooled</ingredient>
  <step>Turn on oven to 180C.</step>
  <step>Grease rectangular dish and line with grease proof paper, then set aside.</step>
  <step>Place dry ingredients in a bowl and stir to combine.</step>
  <step>Stir in coconut oil then combined milk and eggs.</step>
  <step>Stir well and pour into prepared dish.</step>
  <step>Smooth over top and place in oven for 20 minutes or when centre is cooked.</step>
  <step>Cool on wire rack, sprinkle over a little more cacao powder to decorate.</step>
  <step>Cut into squares, and store in airtight container when completely cool.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/hummingbird_cake.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd"> 
                                                                                
    <title>Hummingbird Cake</title>
    <filename>hummingbird_cake.xml</filename>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    


    <diet>GlutenFree</diet>

    <ingredient>1 can crushed pineapple in juice drained</ingredient>
    <ingredient>2 ripe bananas mushed</ingredient>
    <ingredient>2/3 cup desiccated coconut </ingredient>
    <ingredient>1 cup coconut sugar or substitute with raw sugar </ingredient>
    <ingredient>1 cup coconut flour or almond flour</ingredient>
    <ingredient>1 cup gluten free flour </ingredient>
    <ingredient>2 teaspoon baking powder </ingredient>
    <ingredient>2 teaspoon cinnamon </ingredient>
    <ingredient>2 teaspoon vanilla essence </ingredient>
    <ingredient>4 eggs beaten</ingredient>
    <ingredient>1/2 cup oil (olive or vegetable)</ingredient>
    <ingredient>1 lemon zest</ingredient>

    <step>
Preheat oven to 160C and grease 26cm ring cake tin. In large bowl add pineapple, bananas, lemon zest, coconut, sugar, coconut flour and gluten free flour. In a separate bowl combine all other ingredients and stir with a fork. Add to the other ingredients and fold through. Pour into cake tin and smooth top down with back of a spoon or a wet hand. Place in oven for 40 minutes or until knife once inserted comes out clean. Remove by flipping onto a plate and serve warm or cold. You can ice if desired.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/grandmas_pumkin_soup.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Grandmas Pumkin Soup</title>
<filename>grandmas_pumkin_soup.xml</filename>
<thumbnail>grandmas_pumpkin_soup.jpeg</thumbnail>
<category>Soup</category>
<category>Lunch</category>
<diet>FODMAP</diet>
<diet>Vegetarian</diet>
<yield>6</yield>
<prepTime>PT20M</prepTime>
<cookTime>PT40M</cookTime>
<ingredient>6-10 cups chopped Kent pumpkin</ingredient>
<ingredient>5 cups chopped butternut pumpkin</ingredient>
<ingredient>2-3 large carrots chopped finely</ingredient>
<ingredient>1-3 garlic cloves crushed</ingredient>
<ingredient>1 teaspoon curry power</ingredient>
<ingredient>Olive oil</ingredient>
<ingredient>Chicken stock</ingredient>
<ingredient>Salt and pepper to taste</ingredient>
<ingredient>Fresh nutmeg and cream to serve</ingredient>
<step>Heat oil in a large pot, add garlic and cook a few minutes.</step>
<step>Place a small amount of curry powder in the pot and cook for a few minutes.</step>
<step>Throw in enough of the pumpkin to cover the bottom of the pot.</step>
<step>Stir continuously to coat all sides of the pumpkin then remove from pot.</step>
<step>Cook pumpkin and carrot in batches until all done.</step>
<step>Once all pumpkin and carrot is coated, place back into the pot and add enough stock to cover.</step>
<step>Bring to boil and then lower to a simmer.</step>
<step>Cook until carrots are very soft, then blend with stick blender and add salt and pepper to taste.</step>
<step>Serve in a bowl with a teaspoon of cream poured in the middle and stirred in a circular motion.</step>
<step>Grate fresh nutmeg on top then serve.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/larb.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Larb</title>
<filename>larb.xml</filename>
<thumbnail>larb.jpeg</thumbnail>
<category>Dinner</category>
<category>Lunch</category>
<category>Pork</category>
<diet>FODMAP</diet>
<diet>LowSugar</diet>
<diet>GlutenFree</diet>
<diet>DiaryFree</diet>
<diet>FODMAP</diet>
<diet>LowCarb</diet>
<diet>EggFree</diet>
<yield>6</yield>
<prepTime>PT30M</prepTime>
<cookTime>PT10M</cookTime>
<ingredient>600 gms minced pork </ingredient>
<ingredient>3 Tbsps olive oil </ingredient>
<ingredient>2 garlic cloves crushed</ingredient>
<ingredient>1 inch ginger grated</ingredient>
<ingredient>1/2 teaspoon chilli powder </ingredient>
<ingredient>1-2 limes juiced</ingredient>
<ingredient>1/3 cup fish sauce</ingredient>
<ingredient>1 teaspoon sugar</ingredient>
<ingredient>1/4 cup mint leaves chopped</ingredient>
<ingredient>3 cups rice noodles cooked and chopped</ingredient>
<ingredient>1 lettuce leaves removed</ingredient>
<ingredient>Extra limes to serve</ingredient>
<step>Prepare lettuce leaves and set aside. Google how to easily remove lettuce leaves easily.</step>
<step>Combine lime juice, fish sauce and sugar, stir to combine and set aside.</step>
<step>Heat oil in pan and cook meat until brown.</step>
<step>Add garlic, ginger and chilli and cook a few minutes more.</step>
<step>Pour in juice mixture and stir through with noodles.</step>
<step>Serve inside a lettuce cup with lime on the side.</step>
<step>Alternately serve in rolled lettuce leaves, with thinly sliced cumber, lettuce and some chilli sauce.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/rocky_road.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd">
  <title>Rocky Road</title>
  <filename>rocky_road.xml</filename>
  <thumbnail>rocky_road.jpeg</thumbnail>
  <category>Sweets</category>
  <ingredient>500gms milk chocolate </ingredient>
  <ingredient>200gms dark chocolate </ingredient>
  <ingredient>4 x 55gm bars Turkish Delight</ingredient>
  <ingredient>400gms marshmallows </ingredient>
  <ingredient>1 1/2 cups peanuts chopped </ingredient>
  <ingredient>1 cup coconut </ingredient>
  <ingredient>1 cup rice bubbles</ingredient>
  <step>Spray a 25x15cm tray with oil and push down baking paper to cover tray, then set aside.</step>
  <step>Chop Turkish Delights and set aside.</step>
  <step>Break apart chocolate into small pieces and melt in double pot until all melted.</step>
  <step>Set aside for five minutes.</step>
  <step>Stir in rice bubbles, nuts, coconut and Turkish Delight.</step>
  <step>Then stir through marshmallows and pour into prepared tray.</step>
  <step>Push to sides and smooth over the top a little.</step>
  <step>Cover then put in freezer for 1/2 hour.</step>
  <step>Remove from freezer then chop into bite size pieces.</step>
  <step>Store in airtight container.</step>
</recipe>
