=== cazzscookingcommunity/cazzscookingcommunity.github.io/xml/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommunity.github.io"
xmlns="https://cazzscookingcommunity.github.io"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="lowSugar"/>
        <xs:element name="glutenfFree"/>
        <xs:element name="eggFree"/>
        <xs:element name="vegan"/>
        <xs:element name="vegeterian"/>
        <xs:element name="paleo"/>
        <xs:element name="keto"/>
        <xs:element name="elemination"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
        <xs:enumeration value="ml"/>
        <xs:enumeration value="drops"/>
        <xs:enumeration value="cm"/>
        <xs:enumeration value="inch"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="categoryType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="household"/>
        <xs:enumeration value="breakfast"/>
        <xs:enumeration value="lunch"/>
        <xs:enumeration value="dinner"/>
        <xs:enumeration value="personal"/>
        <xs:enumeration value="soup"/>
        <xs:enumeration value="beef"/>
        <xs:enumeration value="lamb"/>
        <xs:enumeration value="pork"/>
        <xs:enumeration value="poultry"/>
        <xs:enumeration value="fish"/>
        <xs:enumeration value="drink"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="amount" type="xs:float"/>
        <xs:attribute name="unit" type="unitType"/>
</xs:complexType>

<xs:complexType name="partType">
    <xs:sequence>
    <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
    <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="recipeType">
    <xs:sequence>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="comment" type="xs:string"/>
    <xs:element name="thumbnail" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="image" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="diet" type="dietType" minOccurs="0"/>
    <xs:element name="category" type="categoryType"/>
    <xs:element name="yield" type="xs:integer"/>
    <xs:element name="prepTime" type="xs:int"/>
    <xs:element name="cookTime" type="xs:int"/>
    <xs:element name="part" type="partType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/mac_and_cheese_slice.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Mac and Cheese Slice

1 packet macaroni 
400 gms bacon pieces cooked
1 quantity white sauce*
2 TBsp Olive oil 
Grated tasty cheese
SandP to taste

Preheat oven to 180D. Cook macaroni to packet directions and pour 2 Tbsp olive oil and stir to coat all pasta (this stops it sticking together.) Pour into baking dish with all other ingredients except cheese and stir to combine. Top with cheese and bake for 40 minutes or until lightly browned on top.

*White Sauce

125 gms butter
1/3 cup flour 
700 MPs milk
Salt and white pepper to taste

Melt butter on stove top, add flour and stir to combine. Add a little milk and stir well until it thickens. Continually do this until all milk use up. Add SandP to taste.
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/natural_homemade_face_scrub.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Natural Homemade Face Scrub</title>
<filename>natural_homemade_face_scrub.xml</filename>
<thumbnail>natural_homemade_face_scrub.jpeg</thumbnail>
<category>Household</category>
<yield>1</yield>
<prepTime>PT15M</prepTime>
<cookTime>PT10M</cookTime>
<comment>c/o iamvanessae (You Tube)</comment>
<part><title>Coffee Scrub</title>
<ingredient>1/4 cup fresh coffee grounds </ingredient>
<ingredient>2 TBSP coconut oil</ingredient>
<step>Coffee scrub can be used on your body also.</step>
</part>
<part><title>Olive Oil Scrub</title>
<ingredient>3 TBSP olive oil</ingredient>
<ingredient>1/4 cup sugar</ingredient>
<step>Mix ingredients until combine and decant into repurposed jars.</step>
<step>Use once or twice a week.</step>
<step>I use mine while I'm in the shower!</step>
</part>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/coleslaw_dressing.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Coleslaw Dressing </title>
<filename>coleslaw_dressing.xml</filename>
<thumbnail>coleslaw_dressing.jpeg</thumbnail>
<category>Salad</category>
<category>Sides</category>
<diet>GlutenFree</diet>
<diet>Vegetarian</diet>
<yield>4</yield>
<prepTime>PT10M</prepTime>
<cookTime>PT10M</cookTime>
<ingredient>1/4 Mayo</ingredient>
<ingredient>1/2 lemon juiced or 1 lime juiced </ingredient>
<ingredient>1 Tbsp poppyseed </ingredient>
<ingredient>salt and pepper to taste </ingredient>
<step>Mix all ingredients together and add to your coleslaw.</step>
<step>Mix through and serve immediately.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/natural_homemade_face_scrub.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io recipe.xsd"> 
                                                                                
    <title>Natural Homemade Face Scrub</title>
    <filename>natural_homemade_face_scrub.xml</filename>

    <comment>c/o iamvanessae (You Tube)</comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category>Personal</category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>

    <part>
        <title>Coffee Scrub</title>
        <ingredient>1/4 cup fresh coffee grounds </ingredient>
        <ingredient>2 TBSP coconut oil</ingredient>
        <step></step>
    </part>

    <part>
        <title>Olive Oil Scrub</title>
        <ingredient>3 TBSP olive oil</ingredient>
        <ingredient>1/4 cup sugar</ingredient>
        <step>
            Mix ingredients until combine and decant into repurposed jars. Use once or twice a week. (I use mine while Im in the shower!)
            Coffee Scrub can be used on your body also.
        </step>
    </part>


</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/chowder.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
CHOWDER
Gluten Free

1 can creamed corn 
4 potatoes peeled and chopped
2 large carrots chopped
200-300gms diced bacon
2 chicken stock cubes
Milk and Water
Oil
SandP to taste

Heat oil in large pot and cook the bacon until brown.  Add can of creamed corn then fill can with milk and pour into pot then do the same with water. Add all other ingredients and bring to simmer. Cook until veggies are soft, stir every now and then, to stop bottom catching (about 30-45 mins) Serve with thick toast or fresh bread if desired. You can double recipe.  Great for a cold winter lunch!
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/cazzies_smoothy.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd">
  <title>Cazzies Smoothy</title>
  <filename>cazzies_smoothy.xml</filename>
  <thumbnail>cazzie_smoothy.jpeg</thumbnail>
  <category>Drink</category>
  <ingredient>1 old banana</ingredient>
  <ingredient>1/2 cup frozen strawberries </ingredient>
  <ingredient>1/4 frozen raspberries </ingredient>
  <ingredient>1/2 cup vanilla yogurt</ingredient>
  <ingredient>1 cup milk (can substitute with rice, soy, almond ect)</ingredient>
  <step>Place all ingredients in blender and blend until smooth! Serve in tall glass.</step>
  <step>Can be doubled.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/sues_brown_rice_salad.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Sues Brown Rice Salad</title>
<filename>sues_brown_rice_salad.xml</filename>
<thumbnail>sues_brown_rice_salad.jpeg</thumbnail>
<category>Sides</category>
<category>Salad</category>
<category>Lunch</category>
<diet>GFO</diet>
<diet>Vegan</diet>
<diet>LowSugar</diet>
<yield>4</yield>
<prepTime>PT10M</prepTime>
<cookTime>PT10M</cookTime>
<part><title>Dressing</title>
<ingredient>1/4 cup olive oil</ingredient>
<ingredient>3 TBsp soy sauce (GF if necessary)</ingredient>
<ingredient>1 lemon juiced</ingredient>
<ingredient>Pepper to taste</ingredient>
<step>Mix dressing in a small jar and shake.</step>
<step>Pour over rice then add all other ingredients and stir to combine.</step>
<step>This can be served hot or cold as a side or main.</step>
</part>
<part><title>Rice</title>
<ingredient>2-3 cups brown rice cooked</ingredient>
<ingredient>1/2 cup sultanas (or substitute)</ingredient>
<ingredient>1/2 cup cashew (or substitute) slightly pan fried</ingredient>
<ingredient>1 chilli deseeded and finely chopped</ingredient>
<ingredient>2-3 spring onions chopped</ingredient>
<ingredient>1 red pepper chopped</ingredient>
<ingredient>1 can corn drained</ingredient>
<ingredient>1/2 cup seeds</ingredient>
<step>Mix all ingredients together and serve immediately.</step>
</part>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/potatoe_and_leek_soup.xml
<?xml version='1.0' encoding='UTF-8'?>
<recipe xmlns="https://cazzscookingcommunity.github.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cazzscookingcommunity.github.io https://cazzscookingcommunity.github.io/xml/recipe.xsd">
  <title>Potatoe and Leek Soup</title>
  <filename>potatoe_and_leek_soup.xml</filename>
  <thumbnail>../images/potatoe_and_leek_loup.jpeg</thumbnail>
  <category>Soup</category>
  <diet>GlutenFree</diet>
  <diet>Vegan</diet>
  <ingredient>2 leeks white part chopped</ingredient>
  <ingredient>8-10 Potatoes chopped</ingredient>
  <ingredient>3-4 garlic cloves crushed</ingredient>
  <ingredient>2-4 TBsp olive oil</ingredient>
  <ingredient>10 cups stock</ingredient>
  <ingredient>S and white P to taste</ingredient>
  <step>
In a large pot heat oil and slow cook garlic for 5-7 minutes. Add remaining ingredients, except salt and pepper, and bring to the boil. Reduce and simmer until spuds can be crushed easily on the side of the pot (about 30-40 mins.) turn of heat and blend with stick blender, until all combined and smooth. Add salt and pepper to taste. (Re-heat if necessary.) Serve with crusty bread if desired.
    </step>
</recipe>
