=== cazzscookingcommunity/cazzscookingcommunity.github.io/xml/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommunity.github.io"
xmlns="https://cazzscookingcommunity.github.io"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="lowSugar"/>
        <xs:element name="glutenfFree"/>
        <xs:element name="eggFree"/>
        <xs:element name="vegan"/>
        <xs:element name="vegeterian"/>
        <xs:element name="paleo"/>
        <xs:element name="keto"/>
        <xs:element name="elemination"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
        <xs:enumeration value="ml"/>
        <xs:enumeration value="drops"/>
        <xs:enumeration value="cm"/>
        <xs:enumeration value="inch"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="categoryType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="household"/>
        <xs:enumeration value="breakfast"/>
        <xs:enumeration value="lunch"/>
        <xs:enumeration value="dinner"/>
        <xs:enumeration value="personal"/>
        <xs:enumeration value="soup"/>
        <xs:enumeration value="beef"/>
        <xs:enumeration value="lamb"/>
        <xs:enumeration value="pork"/>
        <xs:enumeration value="poultry"/>
        <xs:enumeration value="fish"/>
        <xs:enumeration value="drink"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="amount" type="xs:float"/>
        <xs:attribute name="unit" type="unitType"/>
</xs:complexType>

<xs:complexType name="partType">
    <xs:sequence>
    <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
    <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="recipeType">
    <xs:sequence>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="comment" type="xs:string"/>
    <xs:element name="thumbnail" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="image" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="diet" type="dietType" minOccurs="0"/>
    <xs:element name="category" type="categoryType"/>
    <xs:element name="yield" type="xs:integer"/>
    <xs:element name="prepTime" type="xs:int"/>
    <xs:element name="cookTime" type="xs:int"/>
    <xs:element name="part" type="partType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/large_banana_bread.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>Large Banana Bread</title>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>


    <diet>Super Easy</diet>
    <ingredient>(Good for a crowd or taking somewhere)</ingredient>

    <step>
2 cups flour
1 cup sugar
1/4 teaspoon baking powder
1 teaspoon cinnamon 
2 teaspoon baking soda
1/2 teaspoon salt
1 cup chopped walnuts ( nuts optional)
1 cup oil
1 teaspoon vanilla
3 eggs beaten
2 cups mashed bananas (2-3 bananas)

Turn on oven to 170D. Grease 20cm x 12cm dish or two loaf trays and set aside.  Combine all ingredients, except bananas and mix well. Add bananas and fold through, then pour into prepared tray. Smooth over top and place in oven for 40-60 minutes or until skew come out clean. Remove from oven and cover immediately with foil. Wait 10-15 minutes before serving while warm or wait until completely cold. You can sprinkle with a little icing sugar when serving.

NB-When my bananas go spotty I pop them in the the freezer. When I have three bananas I make a cake. They look pretty horrible when defrosted, but it makes the cake taste awesome!
*Pam Wolfs recipe
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/traditional_shortbread.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Traditional Shortbread

250 gms butter melted
2 cups plain flour sifted
2 TBsp rice flour 
1/3 cup icing or castor sugar sifted

Preheat oven to 160C and grease a baking tray with butter, then set aside. Mix all ingredients in a bowl until combined. Make a ball with the ingredients, with your hands and move to baking tray. Squash down with your hands until it is about 5mm thick and smooth any cracks. Prick entire surface with fork and bake in oven until just golden. Remove from oven and slice with a knife into small rectangles while still hot. Serve when cold.
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/sues_brown_rice_salad.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Sues Brown Rice Salad</title>
  <filename>sues_brown_rice_salad.xml</filename>
  <thumbnail>../images/sues_brown_rice_salad.jpeg</thumbnail>
  <category>Sides</category>
  <part>
    <title>Dressing</title>
    <ingredient>1/4 cup olive oil</ingredient>
    <ingredient>3 TBsp soy sauce</ingredient>
    <ingredient>1 lemon juiced</ingredient>
    <ingredient>Pepper to taste</ingredient>
    <step>Mix dressing in a small jar and shake. Pour over rice then add all other ingredients and stir to combine.</step>
    <step>This can be served hot or cold as a side or main.</step>
  </part>
  <part>
    <title>Rice</title>
    <ingredient>2-3 cups brown rice cooked</ingredient>
    <ingredient>1/2 cup sultanas (or substitute)</ingredient>
    <ingredient>1/2 cup cashew (or substitute) slightly pan fried</ingredient>
    <ingredient>1 chilli deseeded and finely chopped</ingredient>
    <ingredient>2-3 spring onions chopped</ingredient>
    <ingredient>1 red pepper chopped</ingredient>
    <ingredient>1 can corn drained</ingredient>
    <ingredient>1/2 cup seeds</ingredient>
    <step>cook as normal</step>
  </part>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/apple_pie_with_a_twist.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>Apple Pie with a twist</title>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>



    <ingredient>If you hate rolling pastry, but love home made style, this is a good one for you!</ingredient>

    <step>
150 gms butter
2/3 cup sugar
1 large egg
2 1/2 cups flour s
1/3-1/2 cup milk
Pinch of salt
Tin of ready apple pie filling ( if you want to cheat)

Cream sugar and butter, then add egg. Add flour and salt, then milk 1/3 cup first then if it seems dry add the rest to make up to 1/2 cup. Divide in two and roll into balls and wrap in glad wrap and refrigerate for at least an hour. Prepare dish by greasing with a little butter and use your hands to push one ball into the dish to make the base. Pour in apple and make flat with the back of a spoon. Grate the other ball until all used up and top completely covered. Cook in slow oven for one hour. Serve with ice cream and/or cream. Great hot or cold!
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/guacamole.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Guacamole
(Gluten Free, Vegan)

2-3 avocados pitted, peeled and mashed
1 lime juiced
1 tomatoe de-seeded and chopped
3 spring onions chopped
1-2 garlic cloves crushed
1/2 teaspoon chilli powder
SandP to taste

Mix all together and sprinkle a few extra spring onions on top.
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/black_bean_salad.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Black Bean Salad</title>
<filename>black_bean_salad.xml</filename>
<thumbnail>blackbean_salad.jpeg</thumbnail>
<category>Salad</category>
<category>Sides</category>
<diet>GlutenFree</diet>
<diet>Vegan</diet>
<diet>LowSugar</diet>
<yield>6</yield>
<prepTime>PT10M</prepTime>
<cookTime>PT10M</cookTime>
<part><title>Main</title>
<ingredient>1 can black beans rinsed and drained</ingredient>
<ingredient>1 can corn drained</ingredient>
<ingredient>1 red capsicum diced</ingredient>
<ingredient>3-4 spring onions chopped </ingredient>
<ingredient>1/2 bunch parsley finely chopped</ingredient>
<step>Put all Salad ingredients in a medium bowl and stir well to mix.</step>
<step>Place dressing ingredients in a small jar and shake well.</step>
<step>Pour dressing over salad just before serving and mix well.</step>
</part>
<part><title>Dressing</title>
<ingredient>3 TBsp olive oil</ingredient>
<ingredient>1 TBsp balsamic vinegar</ingredient>
<ingredient>1/2 teaspoon Dijon mustard</ingredient>
<ingredient>salt and pepper to taste</ingredient>
<step>Mix all ingredients in jar and shake.</step>
</part>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/adrianas_chicken_chorizo.xml
<?xml version='1.0' encoding='UTF-8'?>
<recipe xmlns="https://cazzscookingcommunity.github.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cazzscookingcommunity.github.io https://cazzscookingcommunity.github.io/xml/recipe.xsd">
  <title>Adrianas Chicken and Chorizo</title>
  <filename>adrianas_chicken_chorizo.xml</filename>
  <thumbnail>../images/adrianas_chicken.jpeg</thumbnail>
  <category>Dinner</category>
  <category>Poultry</category>
  <category>Pork</category>
  <ingredient>4-6 chicken thighs cut into strips</ingredient>
  <ingredient>2 chorizo sausages sliced</ingredient>
  <ingredient>1 can cannoli beans rinsed and drained</ingredient>
  <ingredient>3-4 garlic cloves crushed</ingredient>
  <ingredient>2 tins chopped tomatoes </ingredient>
  <ingredient>1 TBsp Italian herbs</ingredient>
  <ingredient>salt and pepper to taste </ingredient>
  <ingredient>3 TBsp olive oil </ingredient>
  <ingredient>Bunch parsley chopped </ingredient>
  <step>Heat olive oil in a large pan. Cook garlic for a few minutes, then add the chorizo and cooked for about five minutes then remove from pan. Add chicken fillets and cook until all sides are cooked. Put chorizo back in pan, add all other ingredients except parsley.  Put lid on pan and place in preheated oven for 20 minutes.  Remove lid and give it a good stir and sprinkle with parsley. If desired serve with crusty bread, rice or mash spud.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/aunty_jackies_pancakes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe
    xmlns="https://cazzscookingcommunity.github.io"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd"> 
    
<title>Aunty Jackies Pancakes</title>
<filename>aunty_jackies_pancakes.xml</filename>
<thumbnail>aunty_jackies_pancakes.jpeg</thumbnail>
<category>Breakfast</category>
<category>Dessert</category>
<category>Snack</category>
<diet>GFO</diet>
<diet>Vegetarian</diet>
<yield>6</yield>
<prepTime>PT10M</prepTime>
<cookTime>PT30M</cookTime>
<ingredient>1 1/2 cups milk</ingredient>
<ingredient>2 cups SR flour (use GF if necessary)</ingredient>
<ingredient>2 TBSP sugar</ingredient>
<ingredient>1 egg beaten</ingredient>
<step>Whisk flour and sugar together, add milk and egg.</step>
<step>Whisk together until combined and there are no lumps.</step>
<step>Heat fry pan to medium to hot and melt some butter in pan then add 1/4 cup of the mixture.</step>
<step>Turn pancake when bubbles are popping in the middle.</step>
<step>Remove once golden brown.</step>
<step>Continue until all mixture is used.</step>
<step>Serve with your favourite toppings.</step>
</recipe>
